namespace Yugma.Crm.Application.Hr.Employees;

public sealed record EmployeeDto(
    Guid Id,
    string Code,
    string FullName,
    string Email,
    string Phone,
    string Department,
    string Designation,
    string Location,
    string? Manager,
    string EmploymentType,
    string Status,
    DateOnly JoinedAt,
    decimal CtcLakhs,
    byte Performance,
    IReadOnlyList<string> Skills,
    DateTime CreatedAt,
    DateTime? UpdatedAt,
    string? AvatarUrl,
    Guid? HrPartnerId = null,
    string? HrPartner = null,
    string? Gender = null,
    string? Pan = null,
    string? Uan = null,
    string? PfNumber = null,
    string? BankName = null,
    string? BankAccount = null);
